<?php

namespace Ecommerce\EcommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BoutiquesPremiumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoutiquesPremiumRepository extends EntityRepository
{
	 public function byBoutique($boutique)
    {
         $qb = $this->createQueryBuilder('u')
                    ->select('u')
                    ->where('u.boutique = :boutique')
                    ->andWhere('u.disponible = 1')
                    ->orderBy('u.id')
                    ->setParameter('boutique', $boutique);
        return $qb->getQuery()->getResult();
    }
}
