adminBoutiques:
    path:     /
    defaults: { _controller: "EcommerceBundle:BoutiquesAdmin:index" }

adminBoutiques_show:
    path:     /{id}/show
    defaults: { _controller: "EcommerceBundle:BoutiquesAdmin:show" }

adminBoutiques_new:
    path:     /new
    defaults: { _controller: "EcommerceBundle:BoutiquesAdmin:new" }

adminBoutiques_create:
    path:     /create
    defaults: { _controller: "EcommerceBundle:BoutiquesAdmin:create" }
    requirements: { _method: post }

adminBoutiques_edit:
    path:     /{id}/edit
    defaults: { _controller: "EcommerceBundle:BoutiquesAdmin:edit" }

adminBoutiques_update:
    path:     /{id}/update
    defaults: { _controller: "EcommerceBundle:BoutiquesAdmin:update" }
    requirements: { _method: post|put }

adminBoutiques_delete:
    path:     /{id}/delete
    defaults: { _controller: "EcommerceBundle:BoutiquesAdmin:delete" }
    requirements: { _method: post|delete }
