<?php

namespace Proxies\__CG__\Ecommerce\EcommerceBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Boutiques extends \Ecommerce\EcommerceBundle\Entity\Boutiques implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array('image' => NULL);



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {
        unset($this->image);

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @param string $name
     */
    public function __get($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', array($name));

            return $this->$name;
        }

        trigger_error(sprintf('Undefined property: %s::$%s', __CLASS__, $name), E_USER_NOTICE);
    }

    /**
     * 
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', array($name, $value));

            $this->$name = $value;

            return;
        }

        $this->$name = $value;
    }

    /**
     * 
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', array($name));

            return isset($this->$name);
        }

        return false;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'id', 'image', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'categorie', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'utilisateur', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'nom', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'fb', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'twi', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'goog', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'yout', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'description', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'telephone', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'adresseEmail', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'adresse', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'date_creation', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'lng', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'atitud');
        }

        return array('__isInitialized__', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'id', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'categorie', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'utilisateur', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'nom', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'fb', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'twi', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'goog', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'yout', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'description', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'telephone', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'adresseEmail', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'adresse', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'date_creation', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'lng', '' . "\0" . 'Ecommerce\\EcommerceBundle\\Entity\\Boutiques' . "\0" . 'atitud');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Boutiques $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

            unset($this->image);
        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(\Ecommerce\EcommerceBundle\Entity\Media $image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', array($image));

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', array());

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie(\Ecommerce\EcommerceBundle\Entity\Categories $categorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', array($categorie));

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', array());

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtilisateur(\Utilisateurs\UtilisateursBundle\Entity\Utilisateurs $utilisateur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtilisateur', array($utilisateur));

        return parent::setUtilisateur($utilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilisateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilisateur', array());

        return parent::getUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', array($telephone));

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', array());

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation($dateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', array($dateCreation));

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', array());

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage1(\Ecommerce\EcommerceBundle\Entity\Media $image1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage1', array($image1));

        return parent::setImage1($image1);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage1', array());

        return parent::getImage1();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage2(\Ecommerce\EcommerceBundle\Entity\Media $image2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage2', array($image2));

        return parent::setImage2($image2);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage2', array());

        return parent::getImage2();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage3(\Ecommerce\EcommerceBundle\Entity\Media $image3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage3', array($image3));

        return parent::setImage3($image3);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage3', array());

        return parent::getImage3();
    }

    /**
     * {@inheritDoc}
     */
    public function setLng($lng)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLng', array($lng));

        return parent::setLng($lng);
    }

    /**
     * {@inheritDoc}
     */
    public function getLng()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLng', array());

        return parent::getLng();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtitud($atitud)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtitud', array($atitud));

        return parent::setAtitud($atitud);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtitud()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtitud', array());

        return parent::getAtitud();
    }

    /**
     * {@inheritDoc}
     */
    public function setFb($fb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFb', array($fb));

        return parent::setFb($fb);
    }

    /**
     * {@inheritDoc}
     */
    public function getFb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFb', array());

        return parent::getFb();
    }

    /**
     * {@inheritDoc}
     */
    public function setTwi($twi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTwi', array($twi));

        return parent::setTwi($twi);
    }

    /**
     * {@inheritDoc}
     */
    public function getTwi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTwi', array());

        return parent::getTwi();
    }

    /**
     * {@inheritDoc}
     */
    public function setGoog($goog)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGoog', array($goog));

        return parent::setGoog($goog);
    }

    /**
     * {@inheritDoc}
     */
    public function getGoog()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGoog', array());

        return parent::getGoog();
    }

    /**
     * {@inheritDoc}
     */
    public function setYout($yout)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYout', array($yout));

        return parent::setYout($yout);
    }

    /**
     * {@inheritDoc}
     */
    public function getYout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYout', array());

        return parent::getYout();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresseEmail($adresseEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresseEmail', array($adresseEmail));

        return parent::setAdresseEmail($adresseEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresseEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresseEmail', array());

        return parent::getAdresseEmail();
    }

}
